// Self-hosts the two typefaces as unicode-range-split woff2 subsets.
// Google Fonts is never hotlinked: a German court has held that passing a visitor's
// IP to Google that way is an unlawful transfer, and German-speaking visitors are
// this site's largest non-English audience.
import fs from "node:fs";
import path from "node:path";

const OUT_DIR = "src/assets/fonts";
const OUT_CSS = "src/assets/css/fonts.css";

const FAMILIES = [
  { pkg: "@fontsource-variable/inter",          family: "Inter Variable",          prefix: "inter",          subsets: ["latin", "latin-ext", "greek", "greek-ext", "cyrillic", "cyrillic-ext"] },
  { pkg: "@fontsource-variable/source-serif-4", family: "Source Serif 4 Variable", prefix: "source-serif-4", subsets: ["latin", "latin-ext", "greek", "cyrillic", "cyrillic-ext"] },
];

fs.mkdirSync(OUT_DIR, { recursive: true });

let css = `/* Generated by scripts/build-fonts.js - do not edit by hand.
   Inter and Source Serif 4, SIL Open Font License 1.1. Licences: src/assets/fonts/LICENSE-*.txt
   Split by unicode-range so a Greek page never downloads Cyrillic, and vice versa. */\n\n`;
let copied = 0;

for (const fam of FAMILIES) {
  const base = path.join("node_modules", fam.pkg);
  const src = fs.readFileSync(path.join(base, "wght.css"), "utf8");
  const blocks = src.split("@font-face").slice(1);
  for (const subset of fam.subsets) {
    const file = `${fam.prefix}-${subset}-wght-normal.woff2`;
    const block = blocks.find((b) => b.includes(`/files/${file}`) || b.includes(`./files/${file}`));
    if (!block) { console.warn(`  ! no @font-face for ${file}`); continue; }
    const range = block.match(/unicode-range:\s*([^;]+);/);
    if (!range) { console.warn(`  ! no unicode-range for ${file}`); continue; }
    fs.copyFileSync(path.join(base, "files", file), path.join(OUT_DIR, file));
    copied++;
    css += `@font-face {\n  font-family: '${fam.family}';\n  font-style: normal;\n  font-display: swap;\n  font-weight: 100 900;\n  src: url('/assets/fonts/${file}') format('woff2-variations');\n  unicode-range: ${range[1].replace(/\s+/g, " ").trim()};\n}\n\n`;
  }
  fs.copyFileSync(path.join(base, "LICENSE"), path.join(OUT_DIR, `LICENSE-${fam.prefix}.txt`));
}

fs.writeFileSync(OUT_CSS, css);
console.log(`fonts: ${copied} woff2 subsets copied, ${OUT_CSS} written`);
